name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: 1blckhrt/dockerhubrepo

      - name: Build Docker image
        run: docker build -t 1blckhrt/dockerhubrepo .

      - name: Tag Docker image
        run: docker tag 1blckhrt/dockerhubrepo 1blckhrt/dockerhubrepo:${{ steps.extract_version.outputs.version }}

      - name: Push Docker image to Docker Hub
        run: docker push 1blckhrt/dockerhubrepo:${{ steps.extract_version.outputs.version }}

      - name: Curl to nginx webhook
        run: curl 34.224.251.5:9000/hooks/nginx_webhook
